# Generated by Django 2.2.4 on 2019-08-03 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_first', models.CharField(help_text='This field will appear in the website.', max_length=40, verbose_name='First name')),
                ('person_last', models.CharField(help_text='This field will appear in the website.', max_length=40, verbose_name='Last name')),
                ('person_email', models.EmailField(help_text='This field will appear in the website.', max_length=254, verbose_name='Research email')),
                ('person_personalemail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Personal email')),
                ('person_phoneext', models.IntegerField(blank=True, null=True, verbose_name='Phone extension')),
                ('person_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile')),
                ('person_bio', models.TextField(blank=True, default='', help_text='This field will appear in the website.', null=True, verbose_name='Biography')),
                ('person_birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('person_img', models.ImageField(blank=True, help_text='This field will appear in the website.', max_length=150, upload_to='uploads/person/person_img', verbose_name='Picture')),
                ('person_cv', models.FileField(blank=True, help_text='This field will appear in the website.', null=True, upload_to='uploads/person/person_cv', verbose_name='Short Vitae')),
                ('person_room', models.CharField(blank=True, max_length=10, null=True, verbose_name='Room')),
                ('person_emergencycontact', models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='Emergency contacts')),
                ('person_gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, verbose_name='Gender')),
                ('person_active', models.BooleanField(default=True, verbose_name='Active')),
                ('person_cardnum', models.IntegerField(blank=True, null=True, verbose_name='Card number')),
                ('full_name', models.CharField(max_length=150, verbose_name='Name')),
                ('person_middle', models.CharField(blank=True, max_length=100, verbose_name='Middle name')),
                ('person_phone', models.CharField(blank=True, help_text='This field will appear in the website if the next field is checked.', max_length=20, null=True, verbose_name='Contact')),
                ('person_phoneshow', models.BooleanField(default=False, verbose_name='Show this contact in the website')),
                ('person_web', models.URLField(blank=True, help_text='This field will appear in the website.', null=True, verbose_name='Website')),
                ('person_datejoined', models.DateField(blank=True, null=True, verbose_name='Joined date')),
                ('person_end', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('djangouser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['person_first', 'person_last'],
                'permissions': (('app_access_hr', 'Access [Human Resources] app'), ('app_access_people', 'Access [People] app')),
            },
        ),
    ]
