# Generated by Django 2.2.4 on 2019-08-03 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_institution'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=200, verbose_name='Name')),
                ('group_subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('group_web', models.URLField(blank=True, null=True, verbose_name='Web site')),
                ('group_people', models.ImageField(blank=True, null=True, upload_to='uploads/group/group_people', verbose_name='People')),
                ('group_img', models.ImageField(blank=True, null=True, upload_to='uploads/group/group_img', verbose_name='Thumbnail')),
                ('group_desc', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('groupdjango', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_django', to='people.Group', verbose_name='Groups in Django')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('grouptype_id', models.AutoField(primary_key=True, serialize=False)),
                ('grouptype_name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Group type',
                'verbose_name_plural': 'Group - Types',
                'ordering': ['grouptype_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionAffiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='Joined')),
                ('date_left', models.DateField(blank=True, null=True, verbose_name='Left')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='common.Institution')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='people.Person')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='Joined')),
                ('date_left', models.DateField(blank=True, null=True, verbose_name='Left')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Position')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='grouptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.GroupType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='people.GroupMember', to='people.Person', verbose_name='Members'),
        ),
        migrations.AddField(
            model_name='group',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Head', to='people.Person', verbose_name='Head'),
        ),
    ]
