# Generated by Django 2.2.4 on 2019-08-04 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190803_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Position'),
        ),
    ]
